# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=150, unique=True)),
                ('common_name', models.CharField(max_length=150)),
                ('family', models.CharField(blank=True, max_length=150)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('regional_status_2015', models.CharField(blank=True, max_length=50)),
                ('regional_status_2010', models.CharField(blank=True, max_length=50)),
                ('global_status_2015', models.CharField(blank=True, max_length=50)),
                ('status_change_reason', models.CharField(blank=True, max_length=50)),
                ('population_size', models.CharField(blank=True, max_length=50)),
                ('distribution_size', models.CharField(blank=True, max_length=50)),
                ('regional_endemic', models.NullBooleanField()),
                ('conservation_underway', models.TextField(blank=True)),
                ('conservation_proposed', models.TextField(blank=True)),
                ('distribution', models.TextField(blank=True)),
                ('ecology', models.TextField(blank=True)),
                ('identification', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True)),
                ('population_trend', models.TextField(blank=True)),
                ('population_trend_justification', models.TextField(blank=True)),
                ('inclusion_reason', models.TextField(blank=True)),
                ('taxonomy', models.TextField(blank=True)),
                ('threats', models.TextField(blank=True)),
            ],
        ),
    ]
