# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='population_trend',
            new_name='population_justification',
        ),
        migrations.AddField(
            model_name='species',
            name='assessors',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='species',
            name='regional_status_2000',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
