# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160902_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='research_priorities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='species',
            name='reviewers',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
