# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160905_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='regional_endemic',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
