# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160905_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='distribution_size',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='species',
            name='global_status_2015',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='species',
            name='population_size',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='species',
            name='regional_endemic',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='species',
            name='regional_status_2000',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='species',
            name='regional_status_2010',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='species',
            name='regional_status_2015',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='species',
            name='status_change_reason',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
