# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160905_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='assessors',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='species',
            name='reviewers',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
