# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160905_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='distribution_map',
            field=models.ImageField(blank=True, null=True, upload_to='distribution_maps/'),
        ),
    ]
