# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_species_distribution_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='distribution_map',
        ),
    ]
