# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 12:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_species_distribution_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=80)),
                ('middle_initials', models.CharField(blank=True, max_length=80)),
                ('last', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'species'},
        ),
        migrations.RenameField(
            model_name='species',
            old_name='assessors',
            new_name='assessor',
        ),
        migrations.AlterField(
            model_name='species',
            name='conservation_proposed',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='conservation_underway',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='distribution',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='ecology',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='identification',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='inclusion_reason',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='justification',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='population_justification',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='population_trend_justification',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='research_priorities',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='taxonomy',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='threats',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
