# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20170110_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='assessors',
            field=models.ManyToManyField(to='website.Assessor'),
        ),
    ]
