# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_species_assessors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('A', 'Assessor'), ('R', 'Reviewer')], max_length=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='Assessor',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='reviewers',
            new_name='reviewer',
        ),
        migrations.RemoveField(
            model_name='species',
            name='assessors',
        ),
        migrations.AddField(
            model_name='species',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='contribution',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Person'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Species'),
        ),
        migrations.AddField(
            model_name='species',
            name='contributors',
            field=models.ManyToManyField(through='website.Contribution', to='website.Person'),
        ),
    ]
