# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170111_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
