# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170111_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='species',
            old_name='threats',
            new_name='threats_narrative',
        ),
    ]
