# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20170111_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='threats',
            field=models.ManyToManyField(blank=True, to='website.Threat'),
        ),
        migrations.AddField(
            model_name='species',
            name='habitats',
            field=models.ManyToManyField(blank=True, to='website.Habitat'),
        ),
    ]
