# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 14:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20170113_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=500, null=True)),
                ('bibtex', django.contrib.postgres.fields.hstore.HStoreField()),
                ('authors', models.ManyToManyField(blank=True, through='website.Authorship', to='website.Person')),
            ],
        ),
        migrations.AlterModelOptions(
            name='habitat',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['scientific_name'], 'verbose_name_plural': 'species'},
        ),
        migrations.AlterModelOptions(
            name='threat',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='authorship',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Reference'),
        ),
        migrations.AddField(
            model_name='species',
            name='references',
            field=models.ManyToManyField(blank=True, to='website.Reference'),
        ),
    ]
