# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20170113_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='bibtex',
            field=models.TextField(),
        ),
    ]
