# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20170113_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='author',
            field=models.CharField(blank=True, help_text='E.g. (Smith A, 1834)', max_length=150),
        ),
        migrations.AlterField(
            model_name='species',
            name='common_name',
            field=models.CharField(help_text='List multiple common names separated by commas', max_length=150),
        ),
        migrations.AlterField(
            model_name='species',
            name='distribution_size',
            field=models.CharField(blank=True, help_text='Enter description, e.g. 33 522 km2', max_length=80),
        ),
        migrations.AlterField(
            model_name='species',
            name='family',
            field=models.CharField(blank=True, help_text='E.g. Spheniscidae', max_length=150),
        ),
        migrations.AlterField(
            model_name='species',
            name='global_status_2015',
            field=models.CharField(blank=True, help_text='E.g. Critically Endangered [A2bcd+3bc+4bd]', max_length=80),
        ),
        migrations.AlterField(
            model_name='species',
            name='habitats',
            field=models.ManyToManyField(blank=True, help_text='<strong>Start typing to search through options.</strong> ', to='website.Habitat'),
        ),
        migrations.AlterField(
            model_name='species',
            name='population_size',
            field=models.CharField(blank=True, help_text='Enter description, e.g. c. 160 mature individuals (80 breeding pairs)', max_length=80),
        ),
        migrations.AlterField(
            model_name='species',
            name='references',
            field=models.ManyToManyField(blank=True, help_text='<strong>Start typing to search through options. Click the green plus sign to add a new reference. </strong> ', to='website.Reference'),
        ),
        migrations.AlterField(
            model_name='species',
            name='regional_endemic',
            field=models.CharField(blank=True, help_text='Yes, No or Partial', max_length=50),
        ),
        migrations.AlterField(
            model_name='species',
            name='regional_status_2000',
            field=models.CharField(blank=True, help_text='E.g. Vulnerable [C1]', max_length=80),
        ),
        migrations.AlterField(
            model_name='species',
            name='regional_status_2010',
            field=models.CharField(blank=True, help_text='E.g. Critically Endangered [A2bcd+3bc+4bcd]', max_length=80),
        ),
        migrations.AlterField(
            model_name='species',
            name='regional_status_2015',
            field=models.CharField(blank=True, help_text='E.g. Critically Endangered* [C1]', max_length=80),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(help_text='E.g. Eudyptes moseleyi', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='status_change_reason',
            field=models.CharField(blank=True, help_text='E.g. Application of criteria', max_length=150),
        ),
        migrations.AlterField(
            model_name='species',
            name='threats',
            field=models.ManyToManyField(blank=True, help_text='<strong>Start typing to search through options.</strong> ', to='website.Threat'),
        ),
    ]
